### ISSUE TITLE
As an unregistered player, I want to be able to create login credentials (i.e., username and password that are both not empty words) to access my game account so I can play games and use other functions that are exclusively available to registered players.

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#1]
- [x] Upon successful registration, the player is automatically logged in and the lobby page is shown. 
- [x] Both fields are required data fields - error alert “Cannot be empty” should be shown if the player clicks on Register with any of the fields left blank. 
- [x] If username entered already exists in the system - error alert “Username has been taken”. 
- [x] Logged-in users can log out and log back to the homepage. 

- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#7
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#63
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#6
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#105
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#66
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#33
