### ISSUE TITLE
As a playing User, I want to be able to move pieces as specified in the rules in order to play the game correctly.

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#10]
- [x] All pieces can move one square up, down, left or right with some exceptions 
- [x] Mines and Flags cannot move. 
- [x] Scouts can move an unlimited number of empty squares in one direction. 
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#41
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#84
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#13
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#10
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#35
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#90
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#93
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#102
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#106
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#60

**Comment by ShiranLiu** [comment]
tentative version: a very detailed skeleton code of the design, which might have errors and to be finalised and test together with front-end development. Since we cannot implement every perfectly at the moment due to lake of other implementation detail, such as data converted to back-end, front-end implementation etc.
