### ISSUE TITLE
As a player, I want to be show the board and game related information correctly in order to have a good game experience.

### ISSUE THREAD

**Issue by jiachencindybao** [sopra-fs23-group-22/sopra-fs23-group-22-server#111]
- [x] Players can only see their own half of the board, their opponent's board is not visible.
- [x] Players can know who the current turn belongs to
- [x] When it's not a player's turn, they cannot move any pieces.
- [x] Players can only move their own pieces.
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#43
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#46
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#112
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#113
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#47
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#115
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#116
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#48
- [x] #119
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#61
