### ISSUE TITLE
As a registered User, I want to be shown an end screen in order to finish games.

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#12]
- [x] A user is shown a victory or lose screen, depending on whether they won or lost. 
- [x] A user wins the game when they capture the flag, or the opponent has no legal moves left. 
- [x] The end screen lets the user return to the lobby or start a new game. 
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#34
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#11
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#36
- [x] #103
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#64
- [x] #136
