### ISSUE TITLE
As a logged in user, I want to see a lobby page where all available rooms are shown in order to create a room or join an existing room.

### ISSUE THREAD

**Issue by jiachencindybao** [sopra-fs23-group-22/sopra-fs23-group-22-server#135]
- [x] In the lobby page, there is a list of available rooms with each one showing “1/2 players” that can be joined. 
- [x] User can click join to join an available room.
- [x] In the lobby page, there is a “create a new “room” button such that the user can create a new room and will be redirected to the new room to wait for the opponent to join. 
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#5
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#70
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#26
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#120
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#27
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#12
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#25
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#92
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#94
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#97
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#118
