### ISSUE TITLE
As a logged-in user, I want to be able to enter the game after another user has joined the room, in order to participate and play.

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#16]
- [x] User who first enters will stay in the room and wait for an opponent to join.
- [x] When there are two players in a room, a user can click button to enter the game.
- [x] Players can see their army type with colored icon in room page.

- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#100
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#104
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#59
