### ISSUE TITLE
As a player, when selecting a piece to move I want the legal moves to be highlighted to easily see the legal moves

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#17]
- [x] Upon clicking a piece, it is highlighted, and the legal moves are displayed. 
- [x] If a piece has no legal moves, there will be no adjacent squares highlighted. 

- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#23
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#23
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#24
