### ISSUE TITLE
As a registered user, I want to search for other users in order to inspect their profiles.

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#3]
- [x] A user can find other users by searching for a username. 
- [x] A user can click other users' usernames to see their profile.
- [x] Users can update their usernames on the profile page.
- [x] Users can check the wins and losses counts on the profile page.

- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#20
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#4
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#3
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#14
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#62
