### ISSUE TITLE
As a registered user, when somebody sends me a friend request, I want to choose whether to accept or reject it. 

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#4]
- [ ] All friend requests received are shown in the "friend request page", which is a small icon accessible in the lobby page.
- [ ] By clicking the accept button, the friend request is approved and both sides will be added to each other’s friend lists. The request then will be inactive. 
- [ ] By clicking the reject button, the request is inactive.  
- [ ] All answered requests are disabled for further action and not shown in the message page anymore.
- [ ] sopra-fs23-group-22/sopra-fs23-group-22-client#31
- [ ] sopra-fs23-group-22/sopra-fs23-group-22-client#18
- [ ] sopra-fs23-group-22/sopra-fs23-group-22-server#59
- [ ] sopra-fs23-group-22/sopra-fs23-group-22-client#8
- [ ] sopra-fs23-group-22/sopra-fs23-group-22-server#61
