### ISSUE TITLE
As a logged-in user, I want to access an ongoing game via a shared link in order to watch my friends playing the game. 

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#7]
- [ ] A logged-in or unlogged-in user could redirect to the game page by clicking an invitation link. 
- [ ] sopra-fs23-group-22/sopra-fs23-group-22-server#52
- [ ] sopra-fs23-group-22/sopra-fs23-group-22-server#53
- [ ] sopra-fs23-group-22/sopra-fs23-group-22-client#29
