### ISSUE TITLE
As a registered User, I want to be able to place my pieces on the board before the game in order to be prepared for the game to start.

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#9]
- [x] A user can start placing his pieces onto the board before the game has started. 
- [x] The game will not start unless both players have placed their pieces. 
- [x] A user can only place pieces in his own half of the board. 
- [x] Each user must place his 40 units, no more, no less. 
- [x] Before all the pieces have been placed onto the board, the “confirm” button is disabled. 
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#27
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#46
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#81
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#82
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#16
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#83
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#30
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#49
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#88
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#91
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#95
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#99
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#39

**Comment by ShiranLiu** [comment]
tentative version: a very detailed skeleton code of the design, which might have errors and to be finalised and test together with front-end development. Since we cannot implement every perfectly at the moment due to lake of other implementation detail, such as data converted to back-end, front-end implementation etc.
